# SPDX-FileCopyrightText: 2021 Carnegie Mellon University
#
# SPDX-License-Identifier: CC0-1.0

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
      - id: pyupgrade
        name: Modernize python code
#        args: ["--py3-only"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: Reorder python imports with isort

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        name: Format python code with black
        language_version: python3

  - repo: https://github.com/asottile/yesqa
    rev: v1.2.3
    hooks:
      - id: yesqa

#  - repo: https://github.com/PyCQA/flake8
#    rev: 3.9.2
#    hooks:
#      - id: flake8
#        name: Lint python code with flake8
#        additional_dependencies: [flake8-bugbear]

  - repo: https://github.com/fsfe/reuse-tool
    rev: v0.13.0
    hooks:
      - id: reuse
        name: Check if all files have a SPDX license identifier
